version: '2.4'
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
  configserver:
    build: exemplo.springcloudconfig.server
    environment:
    - SPRING_RABBITMQ_HOST=rabbitmq 
    - SERVER_PORT=9999
    - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=${SPRING_CLOUD_CONFIG_SERVER_GIT_URI:-https://github.com/justiandre/exemplo.springcloudconfig.config.repo}
    ports:
    - 9999:9999
    healthcheck:
      test: "curl -f http://localhost:9999/health || exit 1"
      interval: 1s
      timeout: 10s
      retries: 60
      start_period: 5s
    depends_on:
      - rabbitmq
  service01:
    build: exemplo.springcloudconfig.service01
    ports:
    - 8080:8080
    environment:
    - SPRING_RABBITMQ_HOST=rabbitmq     
    - SPRING_CLOUD_CONFIG_URI=http://configserver:9999 
    - SERVER_PORT=8080
    depends_on:
      configserver:
        condition: service_healthy
  service02:
    build: exemplo.springcloudconfig.service02
    ports:
    - 8081:8081
    environment:
    - SPRING_RABBITMQ_HOST=rabbitmq     
    - SPRING_CLOUD_CONFIG_URI=http://configserver:9999 
    - SERVER_PORT=8081
    depends_on:
      configserver:
        condition: service_healthy